[package]
name = "crlf_service"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.48", features = [ "full", "extra-traits" ] }
quote = "1.0.35"
convert_case = "0.6.0"
